// playground/app1/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'
// DEFINED IN TYPES
import {emitter} from 'virtual:mariner-root'
// import {emitter as root} from 'virtual:mariner-lighthouse'
console.log(emitter)
// console.log(root)
import rootEmmiter from 'virtual:root'
console.log(rootEmmiter)
</script>

<template>
  <div>
    <div>APP 1</div>
    <div>APP 11111</div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// playground/app3/src/App.tsx
import { useEffect, useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'
import rootEmmiter from 'virtual:root'

function App() {

  const [count, setCount] = useState(0)

  useEffect(() => {
    console.log('what')
    const update = () => {
      
      setCount((val) => val + 1) }
    rootEmmiter.emitter.on('count', update)

    return () => rootEmmiter.emitter.off('count', update)

  }, [])



const increase = () => {
  setCount(count + 1)
  rootEmmiter.emitter.emit('count')
}
  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={increase}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  )
}

export default App
